name = "cloudflare-slack-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Uncomment to use a custom route
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]
